"""create audio_ingest & video_ingest

Revision ID: 31f9322caea1
Revises: 3d0bb1a8a1d4
Create Date: 2025-09-25 01:32:48.272317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f9322caea1'
down_revision: Union[str, Sequence[str], None] = '3d0bb1a8a1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.create_table('audio_ingest',
    sa.Column('audio_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('preprocessed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('processed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_video', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded','processing','completed','failed')", name='audio_ingest_status_check'),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_index('idx_audio_created_at', 'audio_ingest', ['created_at'], unique=False)
    op.create_index('idx_audio_is_video', 'audio_ingest', ['is_video'], unique=False)
    op.create_index('idx_audio_status', 'audio_ingest', ['status'], unique=False)
    op.create_index('idx_audio_user_id', 'audio_ingest', ['user_id'], unique=False)
    op.create_table('video_ingest',
    sa.Column('video_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('audio_id', sa.UUID(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_ingest.audio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id'),
    sa.UniqueConstraint('audio_id')
    )
    op.create_index('idx_video_ingest_audio_id', 'video_ingest', ['audio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_video_ingest_audio_id', table_name='video_ingest')
    op.drop_table('video_ingest')
    op.drop_index('idx_audio_user_id', table_name='audio_ingest')
    op.drop_index('idx_audio_status', table_name='audio_ingest')
    op.drop_index('idx_audio_is_video', table_name='audio_ingest')
    op.drop_index('idx_audio_created_at', table_name='audio_ingest')
    op.drop_table('audio_ingest')
    # ### end Alembic commands ###
